### ISSUE TITLE
Doesn's seem to work on Ruby 1.9.2

### ISSUE THREAD

**Issue by jfrolich** [forward/mandy#2]
Mandy does not seem to work under on Ruby 1.9.2 I get this error. Under 1.8.7 it's fine.

```
/Users/jfrolich/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': no such file to load -- xml/libxml (LoadError)
    from /Users/jfrolich/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/jfrolich/.rvm/gems/ruby-1.9.2-p180/gems/mandy-0.5.26/lib/mandy/ruby-hbase.rb:6:in `<top (required)>'
    from /Users/jfrolich/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/jfrolich/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/jfrolich/.rvm/gems/ruby-1.9.2-p180/gems/mandy-0.5.26/lib/mandy.rb:32:in `block in <top (required)>'
    from /Users/jfrolich/.rvm/gems/ruby-1.9.2-p180/gems/mandy-0.5.26/lib/mandy.rb:9:in `each'
    from /Users/jfrolich/.rvm/gems/ruby-1.9.2-p180/gems/mandy-0.5.26/lib/mandy.rb:9:in `<top (required)>'
    from /Users/jfrolich/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:58:in `require'
    from /Users/jfrolich/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:58:in `rescue in require'
    from /Users/jfrolich/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:35:in `require'
    from square.rb:2:in `<main>'
```

**Comment by andykent** [comment]
I think there is a missing dep in the gemspec. Make sure you have the gem libxml-ruby installed in your 1.9.2 environment and hopefully all should be good.

I'll leave the issue open until the gemspec gets fixed.
